version: '3.1'

services:
  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admin

  niklucy:
    build: .
    depends_on:
      - db
    ports:
      - 80:5000
